source 'https://github.com/shiguredo/sora-ios-sdk-specs.git'
source 'https://cdn.cocoapods.org/'

platform :ios, '13.0'

target 'SpotlightSample' do
  use_frameworks!
  pod 'Sora', '2022.5.0'

  pod 'SwiftLint'
  pod 'SwiftFormat/CLI'
end

post_install do |installer|
  target_names = ["Sora", "Pods-SpotlightSample", "WebRTC"]

  target_names.each do |target_name|
      # 変更対象のターゲット を探す
      pods_target = installer.pods_project.targets.find{ |target| target.name == target_name }
      unless pods_target
          raise ::Pod::Informative, "Failed to find '" << target_name << "' target"
      end

      # ビルド設定を追加
      pods_target.build_configurations.each do |config|
          config.build_settings['ENABLE_BITCODE'] = 'NO'
      end
  end
end