source 'https://github.com/shiguredo/sora-ios-sdk-specs.git'
source 'https://cdn.cocoapods.org/'

platform :ios, '14.0'

target 'SpotlightSample' do
  use_frameworks!
  pod 'Sora', '2025.1.0'

  pod 'SwiftLint'
  pod 'SwiftFormat/CLI'
end
