source 'https://github.com/shiguredo/sora-ios-sdk-specs.git'
source 'https://github.com/CocoaPods/Specs.git'

platform :ios, '10.0'

target 'DecoStreamingSample' do
  use_frameworks!
  pod 'Sora', '2020.7'
end
