source 'https://github.com/shiguredo/sora-ios-sdk-specs.git'
source 'https://github.com/CocoaPods/Specs.git'

platform :ios, '12.1'

target 'DecoStreamingSample' do
  use_frameworks!
  pod 'Sora', '2021.2.1'
end
