source "https://github.com/shiguredo/sora-ios-sdk-specs.git"
source "https://cdn.cocoapods.org/"

platform :ios, "15.0"

target "VideoChatSample" do
  use_frameworks!
  pod "Sora", :git => "https://github.com/shiguredo/sora-ios-sdk.git", :branch => "feature/swiftui"

  pod "SwiftLint"
  pod "SwiftFormat/CLI"
end
