source 'https://github.com/shiguredo/sora-ios-sdk-specs.git'
source 'https://cdn.cocoapods.org/'

platform :ios, '13.0'

target 'VideoGraphSample' do
  use_frameworks!
  #pod 'Sora', '2021.3.1'
  pod 'Sora', :git => 'https://github.com/shiguredo/sora-ios-sdk.git', :branch => 'feature/video-graph-proto'

  pod 'SwiftLint'
  pod 'SwiftFormat/CLI'
end
