source 'https://github.com/shiguredo/sora-ios-sdk-specs.git'
source 'https://cdn.cocoapods.org/'

platform :ios, '13.0'

target 'ScreenCastSample' do
  use_frameworks!
  pod 'Sora', '2022.2.0'

  pod 'SwiftLint'
  pod 'SwiftFormat/CLI'
end
