source 'https://github.com/shiguredo/sora-ios-sdk-specs.git'
source 'https://cdn.cocoapods.org/'

platform :ios, '13.0'

target 'ScreenCastSample' do
  use_frameworks!
  pod 'Sora', '2023.3.0'

#  SwiftLint, SwiftFormat/CLI が Swift 5.8 に対応していないため一時的にコメントアウトする
#  pod 'SwiftLint'
#  pod 'SwiftFormat/CLI'
end
