name: Build DecoStreamingSample

defaults:
  run:
    working-directory: ./DecoStreamingSample

on:
  push:
    paths-ignore:
    - 'README.md'
    - 'CHANGES.md'
    - 'LICENSE'

jobs:
  build:
    runs-on: macos-15
    env:
      XCODE: /Applications/Xcode_16.2.app
      XCODE_SDK: iphoneos18.2
      PROJECT: DecoStreamingSample
      SCHEME: DecoStreamingSample
    steps:
    - uses: actions/checkout@v4
    - name: Select Xcode Version
      run: sudo xcode-select -s '${{ env.XCODE }}/Contents/Developer'
    - name: Show Xcode Version
      run: xcodebuild -version
    - name: Show CocoaPods Version
      run: pod --version
    - name: Restore Pods
      uses: actions/cache@v4
      with:
        path: Pods
        key: ${{ runner.os }}-pods-${{ hashFiles('**/Podfile.lock') }}
        restore-keys: |
          ${{ runner.os }}-pods-
    - name: Install Dependences
      run: |
        pod repo update
        pod install
    - name: Create Environment.swift
      run: |
        cp DecoStreamingSample/Environment.example.swift DecoStreamingSample/Environment.swift
    - name: Build Xcode Project
      run: |
        set -o pipefail && \
          xcodebuild \
            -project '${{ env.PROJECT }}.xcodeproj' \
            -scheme '${{ env.SCHEME }}' \
            -sdk ${{ env.XCODE_SDK }} \
            -arch arm64 \
            -configuration Release \
            -derivedDataPath build \
            clean build \
            CODE_SIGNING_REQUIRED=NO \
            CODE_SIGNING_ALLOWED=NO \
            CODE_SIGN_IDENTITY= \
            PROVISIONING_PROFILE= \
            ASSETCATALOG_COMPILER_GENERATE_ASSET_SYMBOLS=NO
    - name: Check uncommitted unformatted code
      run: |
        ../lint-format.sh