name: Build ScreenCastSample

defaults:
  run:
    working-directory: ./ScreenCastSample

on:
  push:
    paths-ignore:
    - 'README.md'
    - 'CHANGES.md'
    - 'LICENSE'

jobs:
  build:
    runs-on: macos-15
    env:
      XCODE: /Applications/Xcode_16.2.app
      XCODE_SDK: iphoneos18.2
      PROJECT: ScreenCastSample
      SCHEME: ScreenCastSample
    steps:
    - uses: actions/checkout@v4
    - name: Select Xcode Version
      run: sudo xcode-select -s '${{ env.XCODE }}/Contents/Developer'
    - name: Show Xcode Version
      run: xcodebuild -version
    - name: Create Environment.swift
      run: |
        cp ScreenCastSample/Environment.example.swift ScreenCastSample/Environment.swift
    # Build Xcode Project の補足コメント
    #
    # `-skipPackagePluginValidation` は SwiftLintPlugin の実行を許可するために入れてある。
    # この設定がないと、ビルド時に `error: “SwiftLintBuildToolPlugin” must be enabled before it can be used` というエラーが出てしまう
    - name: Build Xcode Project
      run: |
        set -o pipefail && \
          xcodebuild \
            -project '${{ env.PROJECT }}.xcodeproj' \
            -scheme '${{ env.SCHEME }}' \
            -sdk ${{ env.XCODE_SDK }} \
            -arch arm64 \
            -configuration Release \
            -derivedDataPath build \
            -skipPackagePluginValidation \
            clean build \
            CODE_SIGNING_REQUIRED=NO \
            CODE_SIGNING_ALLOWED=NO \
            CODE_SIGN_IDENTITY= \
            PROVISIONING_PROFILE= \
            ASSETCATALOG_COMPILER_GENERATE_ASSET_SYMBOLS=NO
    - name: Check uncommitted unformatted code
      run: |
        cp ../Makefile .
        make fmt-lint